name: Continous Integration

on:
  push:
    paths: ".github/workflows/ci.yml"
    paths: "build.zig"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig build test